[package]
name = "erofs"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Embedded Rust EROFS reader and filesystem builder"
autobins = false

[lib]
path = "src/main.rs"

[[bin]]
name = "extract-erofs"
path = "src/bin/extract-erofs.rs"

[[bin]]
name = "mkfs-erofs"
path = "src/bin/mkfs-erofs.rs"

[dependencies]
anyhow.workspace = true
crc32c.workspace = true
serde.workspace = true
serde_json.workspace = true
regex = "1"
shlex.workspace = true
libc.workspace = true
lz4-sys.workspace = true
sha2.workspace = true
zstd.workspace = true
clap.workspace = true
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[target.'cfg(windows)'.dev-dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_Security", "Win32_System_Memory"] }

[target.'cfg(unix)'.dependencies]
xattr = "1"

